In [2]:
import numpy as np

a = np.array([3,4,6,8,10,12])

In [13]:
a[(a>7) & (a>10)]

array([12])

In [3]:
a[1:3]

array([4, 6])

In [13]:
a.shape

(6,)

In [16]:
a1 = a.reshape(6,1)
a2 = a.reshape(3,2)
a3= a.reshape(2,3)
a4 = a.reshape(1,6)


ValueError: cannot reshape array of size 6 into shape (2,6)

In [15]:
a4

array([[ 3,  4,  6,  8, 10, 12]])

## PANDAS

In [20]:
import pandas as pd

In [21]:
'''
A  B  C  D  E
1  2  8  7  8
12 13 22 21 14 
'''

df = pd.DataFrame()

In [22]:
type(df)

pandas.core.frame.DataFrame

In [23]:
'''
A  B  C  D  E
1  2  8  7  8
12 13 22 21 14 
'''
df = pd.DataFrame(
    {'A': [1,12],
     'B': [2,13],
     'C': [8,22],
     'D': [7,21],
     'E': [8,14]}
)

In [24]:
df

A   B   C   D   E
0   1   2   8   7   8
1  12  13  22  21  14

In [27]:
df1 = pd.DataFrame(
    {'A': [1,12,23,12,34,56,7,8,9],
     'B': [2,13,22,33,44,55,66,77,100],
     'C': [8,22,45,56,77,89,90,98,87],
     'D': [7,21,12,33,44,33,55,66,77],
     'E': [8,14,21,32,43,54,65,76,76]}
)

In [28]:
df1.head()

A   B   C   D   E
0   1   2   8   7   8
1  12  13  22  21  14
2  23  22  45  12  21
3  12  33  56  33  32
4  34  44  77  44  43

In [30]:
df1.tail()

A    B   C   D   E
4  34   44  77  44  43
5  56   55  89  33  54
6   7   66  90  55  65
7   8   77  98  66  76
8   9  100  87  77  76

In [32]:
df1x = df1.head(7)

In [33]:
df1x

A   B   C   D   E
0   1   2   8   7   8
1  12  13  22  21  14
2  23  22  45  12  21
3  12  33  56  33  32
4  34  44  77  44  43
5  56  55  89  33  54
6   7  66  90  55  65

In [37]:
'''
df1 = pd.DataFrame(
    {'A': [1,12,23,12,34,56,7,8,9],
     'B': [2,13,22,33,44,55,66,77,100],
     'C': [8,22,45,56,77,89,90,98,87],
     'D': [7,21,12,33,44,33,55,66,77],
     'E': [8,14,21,32,43,54,65,76,76]}
)'''

data = [[1,12,23,12,34],
        [2,13,22,33,44],
        [8,22,45,56,77],
        [8,14,21,32,43]]

col_names = ['A', 'B', 'C', 'D', 'E']

df2 = pd.DataFrame(data, columns=col_names)

In [38]:
df2

A   B   C   D   E
0  1  12  23  12  34
1  2  13  22  33  44
2  8  22  45  56  77
3  8  14  21  32  43

In [39]:

df2 = pd.DataFrame(
    [[1,12,23,12,34],
     [2,13,22,33,44],
     [8,22,45,56,77],
     [8,14,21,32,43]],
    columns = ['A', 'B', 'C', 'D', 'E']
)


In [41]:
df2

A   B   C   D   E
0  1  12  23  12  34
1  2  13  22  33  44
2  8  22  45  56  77
3  8  14  21  32  43

In [43]:
df1.head()

A   B   C   D   E
0   1   2   8   7   8
1  12  13  22  21  14
2  23  22  45  12  21
3  12  33  56  33  32
4  34  44  77  44  43

In [45]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       9 non-null      int64
 1   B       9 non-null      int64
 2   C       9 non-null      int64
 3   D       9 non-null      int64
 4   E       9 non-null      int64
dtypes: int64(5)
memory usage: 488.0 bytes


In [59]:
df1 = pd.DataFrame(
    {'A': [1,12,23,12,34,56,7,8,np.nan],
     'B': [2,13,22,33,44,55,66,77,'100'],
     'C': [8,22,45,56,77,89,90,98,87],
     'D': [7,21,12,33,44,33,55,66,77],
     'E': [8,14,21,32,43,54,65,76,76]}
)

In [60]:
df1.tail()

A    B   C   D   E
4  34.0   44  77  44  43
5  56.0   55  89  33  54
6   7.0   66  90  55  65
7   8.0   77  98  66  76
8   NaN  100  87  77  76

In [62]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   A       8 non-null      float64
 1   B       9 non-null      object 
 2   C       9 non-null      int64  
 3   D       9 non-null      int64  
 4   E       9 non-null      int64  
dtypes: float64(1), int64(3), object(1)
memory usage: 488.0+ bytes


In [63]:
df1.describe()

A          C          D          E
count   8.000000   9.000000   9.000000   9.000000
mean   19.125000  63.555556  38.666667  43.222222
std    18.114221  32.554228  23.984370  26.109279
min     1.000000   8.000000   7.000000   8.000000
25%     7.750000  45.000000  21.000000  21.000000
50%    12.000000  77.000000  33.000000  43.000000
75%    25.750000  89.000000  55.000000  65.000000
max    56.000000  98.000000  77.000000  76.000000

In [65]:
df1.shape

(9, 5)

In [66]:
df1.columns

Index(['A', 'B', 'C', 'D', 'E'], dtype='object')

In [68]:
df1.dtypes

A    float64
B     object
C      int64
D      int64
E      int64
dtype: object

In [71]:
df1.values

array([[1.0, 2, 8, 7, 8],
       [12.0, 13, 22, 21, 14],
       [23.0, 22, 45, 12, 21],
       [12.0, 33, 56, 33, 32],
       [34.0, 44, 77, 44, 43],
       [56.0, 55, 89, 33, 54],
       [7.0, 66, 90, 55, 65],
       [8.0, 77, 98, 66, 76],
       [nan, '100', 87, 77, 76]], dtype=object)

In [72]:
df.value_counts()

A   B   C   D   E 
1   2   8   7   8     1
12  13  22  21  14    1
Name: count, dtype: int64

In [93]:
df4 = pd.DataFrame(
    {'Animals': ['Cat', 'Dog', 'Cat', 'Cat'],
     'Age': [4,5,6,7],
     'Weight': [12,15,23,20],
   }
)

In [94]:
df4.value_counts()

Animals  Age  Weight
Cat      4    12        1
         6    23        1
         7    20        1
Dog      5    15        1
Name: count, dtype: int64

In [95]:
df4.columns

Index(['Animals', 'Age', 'Weight'], dtype='object')

In [98]:
df4.rename(columns={'Animals': 'Species', 'Age': 'Age in Years', 'Weight': 'Weight in lbs'}, inplace=True)

In [100]:
df1

A    B   C   D   E
0   1.0    2   8   7   8
1  12.0   13  22  21  14
2  23.0   22  45  12  21
3  12.0   33  56  33  32
4  34.0   44  77  44  43
5  56.0   55  89  33  54
6   7.0   66  90  55  65
7   8.0   77  98  66  76
8   NaN  100  87  77  76

In [107]:
df1.sort_values(by=['A', 'B'], ascending=False, inplace=True)

In [108]:
df1

A    B   C   D   E
5  56.0   55  89  33  54
4  34.0   44  77  44  43
2  23.0   22  45  12  21
3  12.0   33  56  33  32
1  12.0   13  22  21  14
7   8.0   77  98  66  76
6   7.0   66  90  55  65
0   1.0    2   8   7   8
8   NaN  100  87  77  76

In [109]:
df1[1:2]

A   B   C   D   E
4  34.0  44  77  44  43

In [113]:
df1.iloc[1:2, :]

A   B   C   D   E
4  34.0  44  77  44  43

In [122]:
df1.loc[1:2, 'D':'E']

Empty DataFrame
Columns: [D, E]
Index: []

In [123]:
df1.sort_index(inplace=True)

In [125]:
df1

A    B   C   D   E
0   1.0    2   8   7   8
1  12.0   13  22  21  14
2  23.0   22  45  12  21
3  12.0   33  56  33  32
4  34.0   44  77  44  43
5  56.0   55  89  33  54
6   7.0   66  90  55  65
7   8.0   77  98  66  76
8   NaN  100  87  77  76

In [124]:
df1.loc[1:2, 'D':'E']

D   E
1  21  14
2  12  21

In [126]:
df1.loc[8:8, 'E':'E']

E
8  76

In [131]:
df1.iloc[8:9, 4:5]

E
8  76

In [133]:
df1.at[8,'E']

76

In [134]:
df1.iat[8,4]

76

In [136]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9 entries, 0 to 8
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   A       8 non-null      float64
 1   B       9 non-null      object 
 2   C       9 non-null      int64  
 3   D       9 non-null      int64  
 4   E       9 non-null      int64  
dtypes: float64(1), int64(3), object(1)
memory usage: 732.0+ bytes


In [138]:
print(df1)

      A    B   C   D   E
0   1.0    2   8   7   8
1  12.0   13  22  21  14
2  23.0   22  45  12  21
3  12.0   33  56  33  32
4  34.0   44  77  44  43
5  56.0   55  89  33  54
6   7.0   66  90  55  65
7   8.0   77  98  66  76
8   NaN  100  87  77  76


In [141]:
df1.iloc[:,2:5]**2

C     D     E
0    64    49    64
1   484   441   196
2  2025   144   441
3  3136  1089  1024
4  5929  1936  1849
5  7921  1089  2916
6  8100  3025  4225
7  9604  4356  5776
8  7569  5929  5776

In [144]:
df1.drop(columns=['A'], inplace=True)

In [145]:
df1

B   C   D   E
0    2   8   7   8
1   13  22  21  14
2   22  45  12  21
3   33  56  33  32
4   44  77  44  43
5   55  89  33  54
6   66  90  55  65
7   77  98  66  76
8  100  87  77  76

In [146]:
df1z = df1.drop(columns=['B'])

In [148]:
df1z

C   D   E
0   8   7   8
1  22  21  14
2  45  12  21
3  56  33  32
4  77  44  43
5  89  33  54
6  90  55  65
7  98  66  76
8  87  77  76